version: "3.7"

services:

  node:
    container_name: homullus_node
    image: node:current-slim
    command: ["tail", "-f", "/dev/null"]
    user: root
    environment:
      - NODE_ENV=production
    ports:
      - ${HTTP_PORT}:8080
    working_dir: /app/src
    volumes:
      - ./:/app:delegated
      - homullus_node_modules:/app/src/node_modules
    networks:
      - homullus

networks:
  homullus:
    driver: bridge

volumes:
  homullus_node_modules: