version: "3.7"

services:

  nginx:
    volumes:
      - ./nginx/src:/usr/share/nginx/html:delegated
      - homullus_node_build:/usr/share/nginx/html/build:ro

  node:
    container_name: homullus_node
    image: homullus_node
    volumes:
      - ./node/src:/home/node/app:delegated
      - homullus_node_build:/home/node/app/build
      - homullus_node_modules:/home/node/app/node_modules

networks:
  homullus:
    driver: bridge

volumes:
  homullus_node_build:
  homullus_node_modules:
