version: "3.7"

services:

  nginx:
    container_name: homullus_nginx
    build:
      context: ./
      dockerfile: ./deployment/nginx/Dockerfile
    restart: always
    working_dir: /app/docs
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./docs:/app/docs:delegated
    networks:
      - homullus

  node:
    container_name: homullus_node
    image: node:current-slim
    command: ["tail", "-f", "/dev/null"]
    user: root
    environment:
      - NODE_ENV=production
    working_dir: /app/src
    volumes:
      - ./:/app:delegated
      - homullus_node_modules:/app/src/node_modules

networks:
  homullus:
    driver: bridge

volumes:
  homullus_node_modules: