version: "3.7"

services:

  nginx:
    container_name: homullus_nginx
    image: homullus_nginx
    restart: always
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    networks:
      - homullus

networks:
  homullus:
    driver: bridge
